name: Qit CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Switch to Xcode 16.0
      run: sudo xcode-select --switch /Applications/Xcode_16.0.app

    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 16 Pro,OS=18.1' -scheme 'Qit'
