name: Qit CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Switch to Xcode 14
      run: sudo xcode-select --switch /Applications/Xcode_14.1.app
   
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 14 Pro' -scheme 'Qit'
